In [81]:
import pandas as pd
import psycopg2                             # postgreSQL database driver for python. Basically, it allows python to connect and communicate with 
                                           # postgreSQL database. 
from sqlalchemy import create_engine      # Here, we are creating an engine object from sqlalchemy package.

In [83]:
orders_df = pd.read_csv("data/orders.csv")

In [84]:
orders_df.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [85]:
orders_df.drop('eval_set', inplace=True, axis=1)

In [86]:
orders_df.head()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,1,2,8,NaN
1,2398795,1,2,3,7,15.0
2,473747,1,3,3,12,21.0
3,2254736,1,4,4,7,29.0
4,431534,1,5,4,15,28.0

In [87]:
aisles_df = pd.read_csv("data\aisles.csv")

In [88]:
aisles_df.head()

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

In [95]:
departments_df = pd.read_csv("data\departments.csv")

In [97]:
departments_df.head()

   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol

In [99]:
order_products_df = pd.read_csv("data\order_products.csv")

In [100]:
order_products_df.head()

   order_id  product_id  add_to_cart_order  reordered
0         2       33120                  1          1
1         2       28985                  2          1
2         2        9327                  3          0
3         2       45918                  4          1
4         2       30035                  5          0

In [101]:
products_df = pd.read_csv("data\products.csv")

In [102]:
products_df.head()

,product_id,product_name,aisle_id,department_id
0,1,Chocolate Sandwich Cookies,61,19
1,2,All-Seasons Salt,104,13
2,3,Robust Golden Unsweetened Oolong Tea,94,7
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1
4,5,Green Chile Anytime Sauce,5,13

In [103]:
#connection 
try:
    conn = psycopg2.connect(dbname="ecommerce_analysis", user='postgres', password = 'YOUR_PASSWORD', host ='localhost', port = '5432')
    print("succ")
except:
    print("connection unsucc")

succ

In [105]:
cur = conn.cursor()    
# A cursor is basically a tool that allows Python to execute SQL queries on the database.

In [111]:
engine = create_engine('postgresql+psycopg2://postgres:YOUR_PASSWORD@localhost/ecommerce_analysis')

#SQLAlchemy engine is higher-level database connection. 
# It is commonly used with pandas to read or write data to databases.

In [ ]:
cur.execute("""         
CREATE TABLE aisles(
    aisle_id INTEGER PRIMARY KEY,
    aisle VARCHAR(255)
)
""")

In [61]:
cur.execute("""         
CREATE TABLE departments(
    department_id INTEGER PRIMARY KEY,
    department VARCHAR(255)
)
""")

In [77]:
cur.execute("""         
CREATE TABLE products(
    product_id INTEGER PRIMARY KEY,
    product_name VARCHAR(255),
    aisle_id INTEGER,
    department_id INTEGER,
    FOREIGN KEY (aisle_id) REFERENCES aisles(aisle_id),
    FOREIGN KEY (department_id) REFERENCES departments(department_id)
    
)
""")

In [93]:
cur.execute("""         
CREATE TABLE orders(
    order_id INTEGER PRIMARY KEY,
    user_id INTEGER,
    order_number INTEGER,
    order_dow INTEGER,
    order_hour_of_day INTEGER,
    days_since_prior_order INTEGER
    
)
""")

In [123]:
cur.execute("""         
CREATE TABLE order_products(
    order_id INTEGER,
    product_id INTEGER,
    add_to_cart_order INTEGER,
    reordered INTEGER,
    PRIMARY KEY (order_id, product_id),
    FOREIGN KEY (order_id) REFERENCES orders(order_id),
    FOREIGN KEY (product_id) REFERENCES products(product_id)
)
""")

In [43]:
aisles_df.to_sql('aisles', con=engine, if_exists='append', index=False)

134

In [45]:
departments_df.to_sql('departments', con=engine, if_exists='append', index=False)

21

In [37]:
products_df.to_sql('products', con=engine, if_exists='append', index=False)

688

In [115]:
orders_df.to_sql('orders', con=engine, if_exists='append', index=False, chunksize=10000, method='multi')

3421083

In [117]:
order_products_df.to_sql('order_products', con=engine, if_exists='append', index=False, chunksize=10000, method='multi')

32434489